[PHP]
max_execution_time = 30
memory_limit = 128M
error_reporting = E_ALL
display_errors = On
log_errors = On
error_log = /dev/stderr

[Date]
date.timezone = UTC

[xdebug]
xdebug.mode = debug
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.start_with_request = no